[platformio]
src_dir = .
include_dir = .
default_envs = release

[env:release]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = genericSTM32F446RE
board_build.ldscript = STM32F446XX_FLASH.ld

upload_protocol = stlink
; upload_protocol = custom
; upload_command = /opt/ST/STM32CubeCLT_1.17.0/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

build_src_filter =
    +<Core/Src/>
    +<Core/Src/vcu/>
    +<Core/Src/vcu/drivers/>
    +<Drivers/STM32F4xx_HAL_Driver/Src/>
    -<Drivers/STM32F4xx_HAL_Driver/Src/*_template.c>
    +<*.s>

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F446xx
    -std=gnu23
    -ICore/Inc
    -ICore/Inc/vcu
    -ICore/Inc/vcu/drivers
    -IDrivers/STM32F4xx_HAL_Driver/Inc
    -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
    -IDrivers/CMSIS/Include

lib_deps =
    https://github.com/eagletrt/libcan-sw.git
    https://github.com/eagletrt/libpal-sw.git
