/******************************************************************************
Finite State Machine
Project: steering_wheel_fsm
Description: Steering Wheel FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-06-28 22:06:21 +0200
Generated from: fsm.dot
The finite state machine has:
  14 states
  0 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>
#include <stdbool.h>

/*** USER CODE BEGIN MACROS ***/

#include "pedals.h"
#include "buzzer.h"
#include "logger.h"
#include "can-communications.h"

struct FsmInitData {
    pedals_set_brake_light_callback set_brake_light;
    pedals_get_tick_callback pedals_get_tick;
    buzzer_delay_callback play_sync_buzzer;
    buzzer_off_callback off_buzzer;
    buzzer_on_callback on_buzzer;
    buzzer_tick_callback tick_buzzer;

    struct LoggerConfig logger_config;

    struct CanCommunicationsNetworkConfig can_network_configs[CAN_COMMUNICATION_NETWORK_COUNT];
};

typedef bool (*fsm_shutdown_closed_callback)(void);
typedef void (*fsm_shutdown_set_callback)(bool closed);
typedef uint32_t (*fsm_get_tick_callback)(void);
typedef bool (*fsm_is_button_pressed_callback)(void);
typedef bool (*fsm_is_button_brake_pressed_callback)(void);

struct FsmData {
    fsm_shutdown_closed_callback shutdown_closed;
    fsm_shutdown_set_callback set_shutdown;
    fsm_get_tick_callback get_tick;
    fsm_is_button_pressed_callback is_button_pressed;
    fsm_is_button_brake_pressed_callback is_button_brake_pressed;
};

/*** USER CODE END MACROS ***/

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
/*** USER STATE DATA TYPE BEGIN ***/
typedef void fsm_state_data_t;
/*** USER STATE DATA TYPE END ***/
// Event data object
// By default the struct is empty; put the data of the event inside
// the structure if you need or leave it empty
typedef struct {

    /*** USER CODE BEGIN EVENT_DATA ***/

    /*** USER CODE END EVENT_DATA ***/

} fsm_event_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    FSM_STATE_INIT = 0,
    FSM_STATE_ENABLE_INV_UPDATES,
    FSM_STATE_CHECK_INV_SETTINGS,
    FSM_STATE_IDLE,
    FSM_STATE_FATAL_ERROR,
    FSM_STATE_START_TS_PRECHARGE,
    FSM_STATE_WAIT_TS_PRECHARGE,
    FSM_STATE_START_TS_DISCHARGE,
    FSM_STATE_WAIT_DRIVER,
    FSM_STATE_ENABLE_INV_DRIVE,
    FSM_STATE_DRIVE,
    FSM_STATE_DISABLE_INV_DRIVE,
    FSM_STATE_RE_ENABLE_INV_DRIVE,
    FSM_STATE_WAIT_TS_DISCHARGE,
    FSM_NUM_STATES,
    FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function prototype
typedef fsm_state_t fsm_state_func_t(fsm_state_data_t *data);

/*** USER CODE BEGIN TYPES ***/

/*** USER CODE END TYPES ***/

// Functions to check and trigger an event
bool fsm_is_event_triggered();
void fsm_event_trigger(fsm_event_data_t *event);

// State functions

// Function to be executed in state init
// valid return states: FSM_STATE_ENABLE_INV_UPDATES
fsm_state_t fsm_do_init(fsm_state_data_t *data);

// Function to be executed in state enable_inv_updates
// valid return states: FSM_NO_CHANGE, FSM_STATE_ENABLE_INV_UPDATES, FSM_STATE_CHECK_INV_SETTINGS
fsm_state_t fsm_do_enable_inv_updates(fsm_state_data_t *data);

// Function to be executed in state check_inv_settings
// valid return states: FSM_NO_CHANGE, FSM_STATE_CHECK_INV_SETTINGS, FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_check_inv_settings(fsm_state_data_t *data);

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR, FSM_STATE_START_TS_PRECHARGE
fsm_state_t fsm_do_idle(fsm_state_data_t *data);

// Function to be executed in state fatal_error
// valid return states: FSM_NO_CHANGE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_fatal_error(fsm_state_data_t *data);

// Function to be executed in state start_ts_precharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_START_TS_PRECHARGE, FSM_STATE_WAIT_TS_PRECHARGE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_start_ts_precharge(fsm_state_data_t *data);

// Function to be executed in state wait_ts_precharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_WAIT_TS_PRECHARGE, FSM_STATE_WAIT_DRIVER, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_wait_ts_precharge(fsm_state_data_t *data);

// Function to be executed in state start_ts_discharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_START_TS_DISCHARGE, FSM_STATE_WAIT_TS_DISCHARGE
fsm_state_t fsm_do_start_ts_discharge(fsm_state_data_t *data);

// Function to be executed in state wait_driver
// valid return states: FSM_NO_CHANGE, FSM_STATE_WAIT_DRIVER, FSM_STATE_ENABLE_INV_DRIVE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_wait_driver(fsm_state_data_t *data);

// Function to be executed in state enable_inv_drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_ENABLE_INV_DRIVE, FSM_STATE_DRIVE, FSM_STATE_DISABLE_INV_DRIVE
fsm_state_t fsm_do_enable_inv_drive(fsm_state_data_t *data);

// Function to be executed in state drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_RE_ENABLE_INV_DRIVE, FSM_STATE_DRIVE, FSM_STATE_DISABLE_INV_DRIVE
fsm_state_t fsm_do_drive(fsm_state_data_t *data);

// Function to be executed in state disable_inv_drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_DISABLE_INV_DRIVE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_disable_inv_drive(fsm_state_data_t *data);

// Function to be executed in state re_enable_inv_drive
// valid return states: FSM_STATE_DRIVE
fsm_state_t fsm_do_re_enable_inv_drive(fsm_state_data_t *data);

// Function to be executed in state wait_ts_discharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_WAIT_TS_DISCHARGE
fsm_state_t fsm_do_wait_ts_discharge(fsm_state_data_t *data);

// List of state functions
extern fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES];

// No transition functions

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data);

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#endif
