/******************************************************************************
Finite State Machine
Project: das_fsm
Description: Das FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-08-08 18:53:57 +0200
Generated from: fsm.dot
The finite state machine has:
  3 states
  2 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/
#include "identity-api.h"
#include "logger-api.h"
#include "encoder-api.h"
#include "can-communications-api.h"
/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "idle", "fatal_error" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,        // in state init
    fsm_do_idle,        // in state idle
    fsm_do_fatal_error, // in state fatal_error
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:         init           , idle           , fatal_error     */
    /* init        */ { NULL, fsm_init_done, fsm_fatal_error },
    /* idle        */ { NULL, NULL, fsm_fatal_error },
    /* fatal_error */ { NULL, NULL, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/
bool inverter_reset = false;
/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_INIT ***/
    if (data == NULL) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    struct FsmInitData *init_data = (struct FsmInitData *)data;

    if (init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_PRIMARY].on_receive == NULL || init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_PRIMARY].send == NULL || init_data->logger_config.send == NULL) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (logger_api_init(init_data->logger_config, true) != LOGGER_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (can_communications_api_init(init_data->can_network_configs) != CAN_COMMUNICATION_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (identity_api_init() != IDENTITY_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM INIT] Modules initialized successfully");

    identity_api_send_state(CAN_PRIMARY_DASFRONTFSM_STATUS_INIT);

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_FATAL_ERROR;

    /*** USER CODE BEGIN DO_IDLE ***/
    logger_api_log(LOGGER_LEVEL_INFO, "[FSM IDLE] Entering state idle");

    can_communications_api_process_rx(CAN_COMMUNICATION_NETWORK_PRIMARY);

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM IDLE] FSM data is NULL");
        next_state = FSM_STATE_FATAL_ERROR;
    }
    struct FsmData *fsm_data = (struct FsmData *)data;

    if (fsm_data->get_tick != NULL) {
        identity_api_periodically_send_state(CAN_PRIMARY_DASFRONTFSM_STATUS_IDLE, fsm_data->get_tick());
        identity_api_periodically_send_version(fsm_data->get_tick());
        identity_api_periodically_send_libcan_version(fsm_data->get_tick());

        encoder_api_periodically_send_angle(fsm_data->get_tick());
    } else {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM IDLE] FSM get_tick function is NULL");
        next_state = FSM_STATE_FATAL_ERROR;
    }

    can_communications_api_process_tx(CAN_COMMUNICATION_NETWORK_PRIMARY);

    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_STATE_FATAL_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal_error
// valid return states: FSM_NO_CHANGE
fsm_state_t fsm_do_fatal_error(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FATAL_ERROR ***/

    logger_api_log(LOGGER_LEVEL_ERROR, "[FSM ERR] Entering state fatal_error");

    /*** USER CODE END DO_FATAL_ERROR ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void fsm_init_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_DONE ***/

    /*** USER CODE END INIT_DONE ***/
}

// This function is called in 2 transitions:
// 1. from init to fatal_error
// 2. from idle to fatal_error
void fsm_fatal_error(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FATAL_ERROR ***/

    /*** USER CODE END FATAL_ERROR ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
};

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (cur_state != FSM_STATE_FATAL_ERROR);
    fsm_run_state(cur_state, NULL);
    return 0;
}
#endif
