/******************************************************************************
Finite State Machine
Project: das_fsm
Description: Das FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-08-09 04:04:06 +0200
Generated from: fsm.dot
The finite state machine has:
  3 states
  3 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>
#include <stdbool.h>

/*** USER CODE BEGIN MACROS ***/
#include "logger.h"
#include "can-communications.h"

struct FsmInitData {
    struct LoggerConfig logger_config;

    struct CanCommunicationsNetworkConfig can_network_configs[CAN_COMMUNICATION_NETWORK_COUNT];
};

typedef uint32_t (*fsm_get_tick_callback)(void);

struct FsmData {
    fsm_get_tick_callback get_tick;
};
/*** USER CODE END MACROS ***/

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
/*** USER STATE DATA TYPE BEGIN ***/
typedef void fsm_state_data_t;
/*** USER STATE DATA TYPE END ***/
// Event data object
// By default the struct is empty; put the data of the event inside
// the structure if you need or leave it empty
typedef struct {
  
  /*** USER CODE BEGIN EVENT_DATA ***/
  
  /*** USER CODE END EVENT_DATA ***/

} fsm_event_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
  FSM_STATE_INIT = 0,  
  FSM_STATE_IDLE,  
  FSM_STATE_FATAL_ERROR,  
  FSM_NUM_STATES,
  FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function and state transition prototypes
typedef fsm_state_t fsm_state_func_t(fsm_state_data_t *data);
typedef void transition_func_t(fsm_state_data_t *data);

/*** USER CODE BEGIN TYPES ***/

/*** USER CODE END TYPES ***/

// Functions to check and trigger an event
bool fsm_is_event_triggered();
void fsm_event_trigger(fsm_event_data_t *event);

// State functions

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data);

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_idle(fsm_state_data_t *data);

// Function to be executed in state fatal_error
// valid return states: FSM_NO_CHANGE
fsm_state_t fsm_do_fatal_error(fsm_state_data_t *data);


// List of state functions
extern fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES];


// Transition functions
void fsm_init_done(fsm_state_data_t *data);
void fsm_fatal_error(fsm_state_data_t *data);
void fsm_no_error(fsm_state_data_t *data);

// Table of transition functions
extern transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES];

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data);

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#endif
