/******************************************************************************
Finite State Machine
Project: steering_wheel_fsm
Description: Steering Wheel FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-06-28 22:06:21 +0200
Generated from: fsm.dot
The finite state machine has:
  14 states
  0 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/

#include "eagletrt-api.h"
#include "ephorus.h"
#include "logger-api.h"
#include "pedals-api.h"
#include "inverter-api.h"
#include "buzzer-api.h"
#include "can-communications-api.h"
#include "tsac.h"
#include "vehicle-api.h"
#include "tsac-api.h"

/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "enable_inv_updates", "check_inv_settings", "idle", "fatal_error", "start_ts_precharge", "wait_ts_precharge", "start_ts_discharge", "wait_driver", "enable_inv_drive", "drive", "disable_inv_drive", "re_enable_inv_drive", "wait_ts_discharge" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,                // in state init
    fsm_do_enable_inv_updates,  // in state enable_inv_updates
    fsm_do_check_inv_settings,  // in state check_inv_settings
    fsm_do_idle,                // in state idle
    fsm_do_fatal_error,         // in state fatal_error
    fsm_do_start_ts_precharge,  // in state start_ts_precharge
    fsm_do_wait_ts_precharge,   // in state wait_ts_precharge
    fsm_do_start_ts_discharge,  // in state start_ts_discharge
    fsm_do_wait_driver,         // in state wait_driver
    fsm_do_enable_inv_drive,    // in state enable_inv_drive
    fsm_do_drive,               // in state drive
    fsm_do_disable_inv_drive,   // in state disable_inv_drive
    fsm_do_re_enable_inv_drive, // in state re_enable_inv_drive
    fsm_do_wait_ts_discharge,   // in state wait_ts_discharge
};
// No transition functions

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

bool inverter_reset = false;

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_ENABLE_INV_UPDATES
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_ENABLE_INV_UPDATES;

    /*** USER CODE BEGIN DO_INIT ***/

    if (data == NULL) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    struct FsmInitData *init_data = (struct FsmInitData *)data;

    if (init_data->set_brake_light == NULL || init_data->pedals_get_tick == NULL || init_data->play_sync_buzzer == NULL || init_data->on_buzzer == NULL || init_data->off_buzzer == NULL || init_data->tick_buzzer == NULL || init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_PRIMARY].on_receive == NULL || init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_INVERTER].on_receive == NULL || init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_PRIMARY].send == NULL || init_data->can_network_configs[CAN_COMMUNICATION_NETWORK_INVERTER].send == NULL || init_data->logger_config.send == NULL) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (logger_api_init(init_data->logger_config, true) != LOGGER_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (pedals_api_init(init_data->set_brake_light, init_data->pedals_get_tick) != PEDALS_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (buzzer_api_init(init_data->on_buzzer, init_data->off_buzzer, init_data->play_sync_buzzer, init_data->tick_buzzer) != BUZZER_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (can_communications_api_init(init_data->can_network_configs) != CAN_COMMUNICATION_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    inverter_api_init();
    if (inverter_api_attach(EPHORUS_WHEEL_FRONT_LEFT) != INVERTER_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (vehicle_api_init() != VEHICLE_RC_OK) {
        next_state = FSM_STATE_FATAL_ERROR;
    }

    tsac_api_init();

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM INIT] Modules initialized successfully");

    // if initialization goes well
    buzzer_api_set_frequency(1000);
    buzzer_api_set_amplitude(0.33f);
    buzzer_api_set_duration(800);
    buzzer_api_play_sync();

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_ENABLE_INV_UPDATES:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state enable_inv_updates
// valid return states: FSM_NO_CHANGE, FSM_STATE_ENABLE_INV_UPDATES, FSM_STATE_CHECK_INV_SETTINGS
fsm_state_t fsm_do_enable_inv_updates(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_ENABLE_INV_UPDATES ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FMS INVUP] Entering state enable_inv_updates");

    inverter_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);

    next_state = FSM_STATE_CHECK_INV_SETTINGS;

    /*** USER CODE END DO_ENABLE_INV_UPDATES ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ENABLE_INV_UPDATES:
        case FSM_STATE_CHECK_INV_SETTINGS:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state check_inv_settings
// valid return states: FSM_NO_CHANGE, FSM_STATE_CHECK_INV_SETTINGS, FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_check_inv_settings(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_CHECK_INV_SETTINGS ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM INVSET] Entering state check_inv_settings");

    inverter_api_set_speed(EPHORUS_WHEEL_FRONT_LEFT, INVERTER_DEFAULT_SPEED_RPM);
    inverter_api_set_torque(EPHORUS_WHEEL_FRONT_LEFT, 0.0f);

    next_state = FSM_STATE_IDLE;

    /*** USER CODE END DO_CHECK_INV_SETTINGS ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_CHECK_INV_SETTINGS:
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FATAL_ERROR, FSM_STATE_START_TS_PRECHARGE
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_IDLE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM IDLE] Entering state idle");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM IDLE] FSM data is NULL");
        next_state = FSM_STATE_FATAL_ERROR;
    }

    struct FsmData *fsm_data = (struct FsmData *)data;

    if (fsm_data->shutdown_closed == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM IDLE] FSM data shutdown_closed is NULL");
        next_state = FSM_STATE_FATAL_ERROR;
    }

    if (!inverter_reset) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM IDLE] Disarming inverter");
        inverter_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);
        inverter_reset = true;
    }

    if (vehicle_api_get_requested_state() == VEHICLE_REQUESTED_STATE_READY) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM IDLE] Vehicle requested state is READY, starting precharge");
        next_state = FSM_STATE_START_TS_PRECHARGE;
        // TODO: really needed?
        if (!fsm_data->shutdown_closed()) {
            next_state = FSM_STATE_IDLE;
        } else if (!vehicle_api_is_shutdown_end_closed()) {
            next_state = FSM_STATE_IDLE;
        }
    }

    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL_ERROR:
        case FSM_STATE_START_TS_PRECHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal_error
// valid return states: FSM_NO_CHANGE, FSM_STATE_FATAL_ERROR
fsm_state_t fsm_do_fatal_error(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FATAL_ERROR ***/

    logger_api_log(LOGGER_LEVEL_ERROR, "[FSM ERR] Entering state fatal_error");

    /*** USER CODE END DO_FATAL_ERROR ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_FATAL_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

EAGLETRT_STATIC uint32_t precharge_start_time = 0;

// Function to be executed in state start_ts_precharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_START_TS_PRECHARGE, FSM_STATE_WAIT_TS_PRECHARGE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_start_ts_precharge(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_START_TS_PRECHARGE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM SPRE] Entering state start_ts_precharge");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM SPRE] FSM data is NULL");
        return FSM_STATE_FATAL_ERROR;
    }

    struct FsmData *fsm_data = (struct FsmData *)data;

    if (fsm_data->shutdown_closed == NULL || fsm_data->get_tick == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM SPRE] FSM data shutdown_closed or get_tick is NULL");
        return FSM_STATE_FATAL_ERROR;
    }

    if (precharge_start_time == 0) {
        precharge_start_time = fsm_data->get_tick();
    }

    if (fsm_data->get_tick() - precharge_start_time >= TSAC_MAX_START_PRECHARGE_TIME_MS) {
        // timeout
        logger_api_log(LOGGER_LEVEL_WARN, "[FSM SPRE] Precharge timeout");
        precharge_start_time = 0;
        next_state = FSM_STATE_START_TS_DISCHARGE;
    } else {
        enum TsacStatus tsac_status = tsac_api_get_status();
        if (tsac_status == TSAC_STATUS_ON || tsac_status == TSAC_STATUS_PRECHARGING) {
            logger_api_log(LOGGER_LEVEL_INFO, "[FSM SPRE] Precharge started successfully");
            next_state = FSM_STATE_WAIT_TS_PRECHARGE;
        } else if (tsac_status == TSAC_STATUS_OFF) {
            logger_api_log(LOGGER_LEVEL_INFO, "[FSM SPRE] Precharge not started, asking TSAC to power on");
            EAGLETRT_API_UNUSED(tsac_api_ask_power_on());
            next_state = FSM_NO_CHANGE;
        } else if (tsac_status == TSAC_STATUS_FATAL) {
            logger_api_log(LOGGER_LEVEL_ERROR, "[FSM SPRE] TSAC in fatal state");
            next_state = FSM_STATE_START_TS_DISCHARGE;
        }
    }

    // TODO: really needed?
    if (!fsm_data->shutdown_closed()) {
        next_state = FSM_STATE_START_TS_DISCHARGE;
    } else if (!vehicle_api_is_shutdown_end_closed()) {
        next_state = FSM_STATE_START_TS_DISCHARGE;
    }

    /*** USER CODE END DO_START_TS_PRECHARGE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_START_TS_PRECHARGE:
        case FSM_STATE_WAIT_TS_PRECHARGE:
        case FSM_STATE_START_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_ts_precharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_WAIT_TS_PRECHARGE, FSM_STATE_WAIT_DRIVER, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_wait_ts_precharge(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_WAIT_TS_PRECHARGE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM WPRE] Entering state wait_ts_precharge");

    if (data == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM WPRE] FSM data is NULL");
        return FSM_STATE_FATAL_ERROR;
    }

    struct FsmData *fsm_data = (struct FsmData *)data;

    if (fsm_data->shutdown_closed == NULL || fsm_data->get_tick == NULL) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM WPRE] FSM data shutdown_closed or get_tick is NULL");
        return FSM_STATE_FATAL_ERROR;
    }

    if (precharge_start_time == 0) {
        precharge_start_time = fsm_data->get_tick();
    }

    if (fsm_data->get_tick() - precharge_start_time >= TSAC_MAX_PRECHARGE_TIME_MS) {
        // timeout
        logger_api_log(LOGGER_LEVEL_WARN, "[FSM WPRE] Precharge timeout");
        precharge_start_time = 0;
        next_state = FSM_STATE_START_TS_DISCHARGE;
    } else {
        switch (tsac_api_get_status()) {
            case TSAC_STATUS_ON:
                logger_api_log(LOGGER_LEVEL_INFO, "[FSM WPRE] Precharge completed successfully");
                next_state = FSM_STATE_WAIT_DRIVER;
                break;
            case TSAC_STATUS_PRECHARGING:
                logger_api_log(LOGGER_LEVEL_INFO, "[FSM WPRE] Precharge still in progress");
                next_state = FSM_NO_CHANGE;
                break;
            default:
                logger_api_log(LOGGER_LEVEL_ERROR, "[FSM WPRE] TSAC in unexpected state");
                next_state = FSM_STATE_START_TS_DISCHARGE;
                break;
        }
    }

    /*** USER CODE END DO_WAIT_TS_PRECHARGE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_WAIT_TS_PRECHARGE:
        case FSM_STATE_WAIT_DRIVER:
        case FSM_STATE_START_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_ts_discharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_START_TS_DISCHARGE, FSM_STATE_WAIT_TS_DISCHARGE
fsm_state_t fsm_do_start_ts_discharge(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_START_TS_DISCHARGE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM SDIS] Entering state start_ts_discharge");

    enum TsacStatus tsac_status = tsac_api_get_status();
    if (tsac_status == TSAC_STATUS_ON || tsac_status == TSAC_STATUS_PRECHARGING) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM SDIS] TSAC is ON or PRECHARGING, asking TSAC to power off");
        EAGLETRT_API_UNUSED(tsac_api_ask_power_off());
        next_state = FSM_STATE_WAIT_TS_DISCHARGE;
    } else {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM SDIS] TSAC is OFF or in FATAL state, waiting for discharge");
        next_state = FSM_STATE_WAIT_TS_DISCHARGE;
    }

    /*** USER CODE END DO_START_TS_DISCHARGE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_START_TS_DISCHARGE:
        case FSM_STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_driver
// valid return states: FSM_NO_CHANGE, FSM_STATE_WAIT_DRIVER, FSM_STATE_ENABLE_INV_DRIVE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_wait_driver(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_WAIT_DRIVER ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM WDRV] Entering state wait_driver");

    if (tsac_api_get_status() != TSAC_STATUS_ON) {
        logger_api_log(LOGGER_LEVEL_WARN, "[FSM WDRV] TSAC is not ON, starting discharge");
        next_state = FSM_STATE_START_TS_DISCHARGE;
    } else {
        enum VehicleRequestedState requested_state = vehicle_api_get_requested_state();
        if (requested_state == VEHICLE_REQUESTED_STATE_IDLE) {
            logger_api_log(LOGGER_LEVEL_INFO, "[FSM WDRV] Vehicle requested state is IDLE, starting discharge");
            next_state = FSM_STATE_START_TS_DISCHARGE;
        } else if (requested_state == VEHICLE_REQUESTED_STATE_DRIVE) {
            if (vehicle_api_is_driver_ready()) {
                logger_api_log(LOGGER_LEVEL_INFO, "[FSM WDRV] Vehicle requested state is DRIVE and driver is ready");
                next_state = FSM_STATE_ENABLE_INV_DRIVE;
            }
        }
    }

    /*** USER CODE END DO_WAIT_DRIVER ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_WAIT_DRIVER:
        case FSM_STATE_ENABLE_INV_DRIVE:
        case FSM_STATE_START_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state enable_inv_drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_ENABLE_INV_DRIVE, FSM_STATE_DRIVE, FSM_STATE_DISABLE_INV_DRIVE
fsm_state_t fsm_do_enable_inv_drive(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_ENABLE_INV_DRIVE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM EDRV] Entering state enable_inv_drive");

    inverter_api_arm(EPHORUS_WHEEL_FRONT_LEFT);

    const struct EphorusWheelTelemetry *wheel_tlm = inverter_api_wheel_telemetry(EPHORUS_WHEEL_FRONT_LEFT);

    if (vehicle_api_get_requested_state() == VEHICLE_REQUESTED_STATE_IDLE) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM EDRV] Vehicle requested state is IDLE");
        next_state = FSM_STATE_DISABLE_INV_DRIVE;
    } else if (wheel_tlm->ready && wheel_tlm->state == EPHORUS_STATE_DRIVE) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM EDRV] Inverter is ready and in DRIVE state");
        buzzer_api_set_duration(2000);
        buzzer_api_play_async();
        next_state = FSM_STATE_DRIVE;
    }

    if (tsac_api_get_status() != TSAC_STATUS_ON) {
        logger_api_log(LOGGER_LEVEL_WARN, "[FSM EDRV] TSAC is not ON, starting discharge");
        next_state = FSM_STATE_DISABLE_INV_DRIVE;
    }

    /*** USER CODE END DO_ENABLE_INV_DRIVE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ENABLE_INV_DRIVE:
        case FSM_STATE_DRIVE:
        case FSM_STATE_DISABLE_INV_DRIVE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_RE_ENABLE_INV_DRIVE, FSM_STATE_DRIVE, FSM_STATE_DISABLE_INV_DRIVE
fsm_state_t fsm_do_drive(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_DRIVE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM DRIV] Entering state drive");

    const struct EphorusWheelTelemetry *wheel_tlm = inverter_api_wheel_telemetry(EPHORUS_WHEEL_FRONT_LEFT);

    if (vehicle_api_get_requested_state() == VEHICLE_REQUESTED_STATE_IDLE) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM DRIV] Vehicle requested state is IDLE");
        next_state = FSM_STATE_DISABLE_INV_DRIVE;
    } else {
        if (!wheel_tlm->ready || wheel_tlm->state != EPHORUS_STATE_DRIVE) {
            logger_api_log(LOGGER_LEVEL_WARN, "[FSM DRIV] Inverter is not ready or not in DRIVE state");
            // TODO: check how much it faults
            // next_state = FSM_STATE_RE_ENABLE_INV_DRIVE;
            next_state = FSM_STATE_DISABLE_INV_DRIVE;
        } else if (tsac_api_get_status() != TSAC_STATUS_ON || pedals_api_communication_timeout()) {
            logger_api_log(LOGGER_LEVEL_WARN, "[FSM DRIV] TSAC is not ON or pedals communication timeout");
            inverter_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);
            next_state = FSM_STATE_DISABLE_INV_DRIVE;
        } else {
            logger_api_log(LOGGER_LEVEL_INFO, "[FSM DRIV] Inverter is ready and in DRIVE state");
            float requested_torque = pedals_api_get_requested_throttle_torque();
            inverter_api_set_torque(EPHORUS_WHEEL_FRONT_LEFT, requested_torque);

        }
    }

    /*** USER CODE END DO_DRIVE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_RE_ENABLE_INV_DRIVE:
        case FSM_STATE_DRIVE:
        case FSM_STATE_DISABLE_INV_DRIVE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state disable_inv_drive
// valid return states: FSM_NO_CHANGE, FSM_STATE_DISABLE_INV_DRIVE, FSM_STATE_START_TS_DISCHARGE
fsm_state_t fsm_do_disable_inv_drive(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_DISABLE_INV_DRIVE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM DDRV] Entering state disable_inv_drive");

    const struct EphorusWheelTelemetry *wheel_tlm = inverter_api_wheel_telemetry(EPHORUS_WHEEL_FRONT_LEFT);

    if (wheel_tlm->state == EPHORUS_STATE_DRIVE) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM DDRV] Disarming inverter");
        inverter_api_disarm(EPHORUS_WHEEL_FRONT_LEFT);
    } else {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM DDRV] Inverter is not in DRIVE state, starting discharge");
        next_state = FSM_STATE_START_TS_DISCHARGE;
        inverter_reset = false;
    }

    /*** USER CODE END DO_DISABLE_INV_DRIVE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_DISABLE_INV_DRIVE:
        case FSM_STATE_START_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state re_enable_inv_drive
// valid return states: FSM_STATE_DRIVE
fsm_state_t fsm_do_re_enable_inv_drive(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_DRIVE;

    /*** USER CODE BEGIN DO_RE_ENABLE_INV_DRIVE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM REDR] Entering state re_enable_inv_drive");

    /*** USER CODE END DO_RE_ENABLE_INV_DRIVE ***/

    switch (next_state) {
        case FSM_STATE_DRIVE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state wait_ts_discharge
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_WAIT_TS_DISCHARGE
fsm_state_t fsm_do_wait_ts_discharge(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_WAIT_TS_DISCHARGE ***/

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM WDIS] Entering state wait_ts_discharge");

    if (!vehicle_api_is_higher_than_60v()) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM WDIS] TSAC lower than 60V, going to idle");
        next_state = FSM_STATE_IDLE;
    }

    /*** USER CODE END DO_WAIT_TS_DISCHARGE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_WAIT_TS_DISCHARGE:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    return new_state;
};

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
